print("#####################################\n")
print("#                                   #\n")
print("#    Dandy Orlen Jr.Pongpalilu      #\n")
print("#           2410817310018           #\n")
print("#                                   #\n")
print("#####################################\n")